name: Deploy Bean Raid to GitHub Pages

on:
  # Runs on pushes to main branch
  push:
    branches: [main]
  # Allows manual trigger from Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install MD2HTML from GitHub
        run: |
          python -m pip install --upgrade pip
          # Clone the md2html repository
          git clone https://github.com/dober-wow/dober-md-html.git
          # Install all required dependencies
          pip install click markdown beautifulsoup4 watchdog aiohttp
          # Verify installation
          echo "Installed packages:"
          pip list | grep -E "click|markdown|beautifulsoup4|watchdog|aiohttp" || true
          
      - name: Convert Markdown files to HTML
        run: |
          echo "========================================="
          echo "Converting Bean Raid markdown files..."
          echo "========================================="
          
          # Show current directory structure
          echo "Current directory contents:"
          ls -la
          echo "Markdown files found:"
          find . -name "*.md" -type f | head -20
          
          # Create output directory
          mkdir -p _site
          
          # Convert using the cloned md2html tool
          echo "Converting with md2html tool..."
          python dober-md-html/md2html.py convert . --output _site --theme manaforge --recursive --embed-images
          
          echo "========================================="
          echo "Conversion complete!"
          echo "========================================="
          
      - name: Create navigation index.html if needed
        run: |
          # Check if index.html already exists from conversion
          if [ -f "_site/index.html" ]; then
            echo "index.html already exists from conversion, skipping creation"
          else
            echo "No index.html found, creating navigation page..."
            cat > _site/index.html << 'HTML'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Bean Raid Chronicle</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }
                  
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      background: linear-gradient(135deg, #0a0e1a 0%, #1a1f2e 50%, #0a0e1a 100%);
                      color: #e5e7eb;
                      min-height: 100vh;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      padding: 2rem;
                  }
                  
                  .container {
                      max-width: 900px;
                      width: 100%;
                      background: rgba(17, 24, 39, 0.95);
                      border-radius: 20px;
                      padding: 3rem;
                      box-shadow: 0 25px 50px rgba(0, 0, 0, 0.7),
                                  inset 0 1px 0 rgba(255, 255, 255, 0.1);
                      backdrop-filter: blur(10px);
                      border: 1px solid rgba(96, 165, 250, 0.2);
                  }
                  
                  h1 {
                      font-size: 3rem;
                      background: linear-gradient(135deg, #60a5fa 0%, #818cf8 50%, #c084fc 100%);
                      -webkit-background-clip: text;
                      -webkit-text-fill-color: transparent;
                      background-clip: text;
                      margin-bottom: 1rem;
                      text-align: center;
                      letter-spacing: -1px;
                      font-weight: 800;
                  }
                  
                  .subtitle {
                      text-align: center;
                      color: #9ca3af;
                      margin-bottom: 3rem;
                      font-size: 1.1rem;
                      letter-spacing: 2px;
                      text-transform: uppercase;
                  }
                  
                  .nav-section {
                      margin-bottom: 2.5rem;
                  }
                  
                  h2 {
                      color: #60a5fa;
                      margin-bottom: 1.5rem;
                      font-size: 1.3rem;
                      text-transform: uppercase;
                      letter-spacing: 1px;
                      border-bottom: 2px solid rgba(96, 165, 250, 0.3);
                      padding-bottom: 0.5rem;
                  }
                  
                  .nav-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                      gap: 1rem;
                  }
                  
                  .nav-card {
                      background: linear-gradient(135deg, rgba(96, 165, 250, 0.1), rgba(129, 140, 248, 0.1));
                      border: 1px solid rgba(96, 165, 250, 0.3);
                      border-radius: 12px;
                      padding: 1.5rem;
                      text-decoration: none;
                      color: #e5e7eb;
                      transition: all 0.3s ease;
                      display: flex;
                      flex-direction: column;
                      align-items: center;
                      text-align: center;
                  }
                  
                  .nav-card:hover {
                      background: linear-gradient(135deg, rgba(96, 165, 250, 0.2), rgba(129, 140, 248, 0.2));
                      border-color: #60a5fa;
                      transform: translateY(-5px);
                      box-shadow: 0 10px 30px rgba(96, 165, 250, 0.3);
                  }
                  
                  .nav-card .icon {
                      font-size: 2rem;
                      margin-bottom: 0.5rem;
                  }
                  
                  .nav-card .title {
                      font-weight: 600;
                      font-size: 1.1rem;
                      color: #60a5fa;
                  }
                  
                  .nav-card .description {
                      font-size: 0.9rem;
                      color: #9ca3af;
                      margin-top: 0.5rem;
                  }
                  
                  .footer {
                      margin-top: 3rem;
                      text-align: center;
                      color: #6b7280;
                      font-size: 0.9rem;
                      border-top: 1px solid rgba(96, 165, 250, 0.2);
                      padding-top: 2rem;
                  }
                  
                  @media (max-width: 640px) {
                      h1 {
                          font-size: 2rem;
                      }
                      .container {
                          padding: 2rem;
                      }
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Bean Raid Chronicle</h1>
                  <div class="subtitle">An Epic Gaming Adventure</div>
                  
                  <div class="nav-section">
                      <h2>🎮 Main Content</h2>
                      <div class="nav-grid">
                          <a href="characters.html" class="nav-card">
                              <div class="icon">👥</div>
                              <div class="title">Characters</div>
                              <div class="description">Meet the raid party</div>
                          </a>
                      </div>
                  </div>
                  
                  <div class="nav-section">
                      <h2>📅 Weekly Chronicles</h2>
                      <div class="nav-grid">
                          <a href="weeks/week1.html" class="nav-card">
                              <div class="icon">⚔️</div>
                              <div class="title">Week 1 — 8/17</div>
                              <div class="description">Pilot: Beans Before Keys</div>
                          </a>
                          <a href="weeks/week2.html" class="nav-card">
                              <div class="icon">🛡️</div>
                              <div class="title">Week 2 — 8/24</div>
                              <div class="description">Beans vs. Beams</div>
                          </a>
                          <a href="weeks/week3.html" class="nav-card">
                              <div class="icon">🏆</div>
                              <div class="title">Week 3 — 8/31</div>
                              <div class="description">Beans on the Brink</div>
                          </a>
                      </div>
                  </div>
                  
                  <div class="footer">
                      <p>Bean Raid Chronicle © 2024</p>
                      <p>Powered by <a href="https://github.com/dober-wow/dober-md-html" style="color: #60a5fa;">MD2HTML</a></p>
                  </div>
              </div>
          </body>
          </html>
          HTML
            echo "Navigation index.html created successfully!"
          fi
          
      - name: List generated files
        run: |
          echo "Generated files in _site/:"
          if [ -d "_site" ]; then
            find _site -type f -name "*.html" | head -20
          else
            echo "No _site directory found"
          fi
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
